version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: your_desired_password
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: your_desired_password
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: your_desired_password
    ports:
      - 8081:8080
    depends_on:
      - postgres

volumes:
  postgres_data: {}
