name: Update Kubernetes Config - Email Service

on:
  workflow_run:
    workflows: ["Build and Push Docker Image - Email Service"]
    types:
      - completed

jobs:
  update-k8s-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get commit hash from Docker image workflow
        id: get_commit_hash
        run: echo "::set-output name=hash::$(cat $GITHUB_EVENT_PATH | jq -r '.workflow_run.head_commit.id')"

      - name: Fetch Kubernetes configurations from pmw-k8s-configs repository
        run: |
          git clone https://github.com/Stack-Learner/pmw-k8s-configs.git
          cd pmw-k8s-configs/email-service

          pwd
          ls -la

          cat email-deployment.yaml

          sed -i "s|imranstacklearner/email:{{ COMMIT_HASH }}|imranstacklearner/email:${{ steps.get_commit_hash.outputs.hash }}|" email-deployment.yaml
          
          cat email-deployment.yaml

          git add email-deployment.yaml

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          git commit -m "Update image tag to ${{ steps.get_commit_hash.outputs.hash }}"
          
          git status

          git push
