# .github/workflows/build-and-push-email.yaml
name: Build and Push Docker Image - Email Service

on:
  push:
    paths:
      - 'services/email/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      
      - name: Login to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Email service Docker image
        run: |
          cd services/email
          docker build \
            --build-arg REDIS_HOST="${{ secrets.REDIS_HOST }}" \
            --build-arg REDIS_PORT="${{ secrets.REDIS_PORT }}" \
            --build-arg CART_TTL="${{ secrets.CART_TTL }}" \
            --build-arg INVENTORY_SERVICE="${{ secrets.INVENTORY_SERVICE }}" \
            --build-arg RABBITMQ_URL="${{ secrets.RABBITMQ_URL }}" \
            -t $DOCKER_USERNAME/email:${{ steps.commit_hash.outputs.hash }} .
          docker push $DOCKER_USERNAME/email:${{ steps.commit_hash.outputs.hash }}

      - name: Trigger Kubernetes update workflow
        if: success()
        uses: actions/workflow-run-trigger@v1
        with:
          workflow: "Update Kubernetes Config - Email Service"
          token: ${{ secrets.PAT_TOKEN }}


# .github/workflows/update-k8s-config-email.yaml
name: Update Kubernetes Config - Email Service

on:
  workflow_run:
    workflows: ["Build and Push Docker Image - Email Service"]
    types:
      - completed

jobs:
  update-k8s-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Provide the personal access token (PAT) for authentication
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get commit hash from Docker image workflow
        id: get_commit_hash
        run: echo "::set-output name=hash::$(cat $GITHUB_EVENT_PATH | jq -r '.workflow_run.head_commit.id')"

      - name: Fetch Kubernetes configurations from pmw-k8s-configs repository
        run: |
          # Clone the repository containing Kubernetes configurations
          git clone https://github.com/Stack-Learner/pmw-k8s-configs.git
          cd pmw-k8s-configs/email-service

          # Update deployment file for the email service
          sed -i "s|imranstacklearner/email:{{ COMMIT_HASH }}|imranstacklearner/email:${{ steps.get_commit_hash.outputs.hash }}|" email-deployment.yaml
          
          # Stage the modified file for commit
          git add email-deployment.yaml
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "Update image tag to ${{ steps.get_commit_hash.outputs.hash }}"
          git push
