# .github/workflows/build-and-push-email.yaml
name: Build and Push Docker Image - Email Service

on:
  push:
    paths:
      - 'services/email/**'
  workflow_run:
    workflows: ["Update Kubernetes Config - Email Service"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      
      - name: Login to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Email service Docker image
        run: |
          cd services/email
          docker build \
            --build-arg REDIS_HOST="${{ secrets.REDIS_HOST }}" \
            --build-arg REDIS_PORT="${{ secrets.REDIS_PORT }}" \
            --build-arg CART_TTL="${{ secrets.CART_TTL }}" \
            --build-arg INVENTORY_SERVICE="${{ secrets.INVENTORY_SERVICE }}" \
            --build-arg RABBITMQ_URL="${{ secrets.RABBITMQ_URL }}" \
            -t $DOCKER_USERNAME/email:${{ steps.commit_hash.outputs.hash }} .
          docker push $DOCKER_USERNAME/email:${{ steps.commit_hash.outputs.hash }}

