name: Build and Push Docker Images

on:
  push:
    paths:
      - 'services/inventory/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      
      - name: Login to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Cart service Docker image
        run: |
          cd services/inventory
          docker build \
            --build-arg DATABASE_URL=$DATABASE_URL \
            .
          docker push $DOCKER_USERNAME/inventory:${{ steps.commit_hash.outputs.hash }}
